# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - uses: actions/checkout@v3
    - uses: c-hive/gha-yarn-cache@v2
    - name: Install dependencies
      run: yarn install
    - name: Run linter
      run: yarn lint

  tsc:
    runs-on: ubuntu-latest
    name: Types check
    steps:
    - uses: actions/checkout@v3
    - uses: c-hive/gha-yarn-cache@v2
    - name: Install dependencies
      run: yarn install
    - name: Run the types check
      run: yarn tsc

  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v3
    - uses: c-hive/gha-yarn-cache@v2
    - uses: codecov/sg-replay-parser@v3
      with:
        files: ./coverage
    - name: Install dependencies
      run: yarn install
    - name: Run the tests
      run: yarn test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
