# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm i
    - name: Run linter
      run: npm run lint

  tsc:
    runs-on: ubuntu-latest
    name: Types check
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm i
    - name: Run the types check
      run: npm run tsc

  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm i
    - name: Run the tests
      run: npm run test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
