# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - uses: actions/checkout@v3
    - uses: c-hive/gha-yarn-cache@v2
    - run: yarn install
    - run: yarn lint

  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v3
    - uses: c-hive/gha-yarn-cache@v2
    - run: yarn install
    - run: yarn test
